name = "webrtc-form-hosting"
compatibility_date = "2025-03-20"

# Bind KV namespace
[[kv_namespaces]]
binding = "SIGNAL_KV"
id = "1ab7ca6546ff444195215a013928f661" # Replace with your KV namespace ID

# Environment variables for Cloudflare Calls API
[vars]
TURN_KEY_API_TOKEN = "aec4d1a50e9576d79af9a6d2e8e3881e89301d97ec8805ec075f029f96731cfa"
TURN_KEY_ID = "096b68dc56186d7d2da1102df34a8631"